services:
  web:
    build: .
    container_name: api_tarefas
    ports:
      - "8080:8000" # Expondo a aplicação na porta 8080
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} # Defina uma senha para o root
      MYSQL_DATABASE: ${DB_NAME}         # Nome do banco de dados
      MYSQL_USER: ${DB_USER}          # Nome do usuário normal
      MYSQL_PASSWORD: ${DB_PASSWORD}   # Senha do usuário
    ports:
      - "3307:3306" # Porta externa 3307 mapeada para a interna 3306
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
