""" incluindo tabela usuario

Revision ID: 2b375db21b57
Revises: a85a802fcfe3
Create Date: 2025-01-20 17:59:11.468441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b375db21b57'
down_revision: Union[str, None] = 'a85a802fcfe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conta_usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=500), nullable=True),
    sa.Column('password', sa.String(length=20), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conta_usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conta_usuario_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conta_usuario_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_conta_usuario_password'), ['password'], unique=False)

    with op.batch_alter_table('tarefas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_usuario', 'conta_usuario', ['usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarefas', schema=None) as batch_op:
        batch_op.drop_constraint('fk_usuario', type_='foreignkey')
        batch_op.drop_column('usuario_id')

    with op.batch_alter_table('conta_usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conta_usuario_password'))
        batch_op.drop_index(batch_op.f('ix_conta_usuario_nome'))
        batch_op.drop_index(batch_op.f('ix_conta_usuario_id'))

    op.drop_table('conta_usuario')
    # ### end Alembic commands ###
