"""alterando coluna disable para activate

Revision ID: 2ef57d652627
Revises: 7c28564f8ac1
Create Date: 2025-01-20 20:56:30.101103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2ef57d652627'
down_revision: Union[str, None] = '7c28564f8ac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conta_usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.drop_column('disabled')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conta_usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('active')

    # ### end Alembic commands ###
