"""validando cpf

Revision ID: 3e8759199324
Revises: ad1d3713e358
Create Date: 2025-01-22 00:42:45.923409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3e8759199324'
down_revision: Union[str, None] = 'ad1d3713e358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conta_usuario', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=14),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conta_usuario', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=sa.String(length=14),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###
