"""ajuste para validar usuario no banco

Revision ID: 60ad70bf71b0
Revises: 3e8759199324
Create Date: 2025-01-24 01:29:07.871416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60ad70bf71b0'
down_revision: Union[str, None] = '3e8759199324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
