"""atualizando tabela usuario

Revision ID: 7c28564f8ac1
Revises: 2b375db21b57
Create Date: 2025-01-20 20:16:59.360401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7c28564f8ac1'
down_revision: Union[str, None] = '2b375db21b57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conta_usuario', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conta_usuario', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('cpf',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###
