"""iniciando migration

Revision ID: a85a802fcfe3
Revises: 
Create Date: 2025-01-18 17:05:12.043339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a85a802fcfe3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarefas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('nivel_prioridade', sa.String(length=50), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tarefas_id'), 'tarefas', ['id'], unique=False)
    op.create_index(op.f('ix_tarefas_nivel_prioridade'), 'tarefas', ['nivel_prioridade'], unique=False)
    op.create_index(op.f('ix_tarefas_status'), 'tarefas', ['status'], unique=False)
    op.create_index(op.f('ix_tarefas_titulo'), 'tarefas', ['titulo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tarefas_titulo'), table_name='tarefas')
    op.drop_index(op.f('ix_tarefas_status'), table_name='tarefas')
    op.drop_index(op.f('ix_tarefas_nivel_prioridade'), table_name='tarefas')
    op.drop_index(op.f('ix_tarefas_id'), table_name='tarefas')
    op.drop_table('tarefas')
    # ### end Alembic commands ###
