"""ajuste para validar usuario no banco

Revision ID: febb02dec7c5
Revises: 60ad70bf71b0
Create Date: 2025-01-24 01:42:40.724175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'febb02dec7c5'
down_revision: Union[str, None] = '60ad70bf71b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
